name: Reviews

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Execute script
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const fs = require('fs')
              const readline = require('readline');
              const file = readline.createInterface({
                            input: fs.createReadStream('owners'),
                            output: process.stdout,
                            terminal: false
                          });
              const result = {}
              file.on('line', (line) => {
                let myArray = line.split(" ")
                let keys = myArray[0].split("/")
                
                const res = keys.reduce((acc, key, index) => {
                  if(index == keys.length-1) {
                      acc[key] = { reviewers: myArray.slice(1) }
                  }
                  else {
                      acc[key] = { reviewers: [] };
                  }
                  return acc[key];
                }, result); 
            console.log("result: ",JSON.stringify(result, null, 2));
            console.log("res: ",res);
            });
            }
            catch(error) {console.log("Error reading file: ",error)}
          


#  const ownersFileContent = fs.readFileSync('owners', 'utf-8')
#            console.log('ownersFileContent: ',ownersFileContent)
#            }
#            catch(error) {
#            console.error('Error reading file:', error);
#            }
