name: Reviews

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Upload owners file
        uses: actions/upload-artifact@v3
        with:
          name: upload_owners
          path: MyApplication/owners.txt

      - name: Execute script
        uses: actions/github-script@v7
        with:
          script: |
            try {
            const fs = require('fs')
            const ownersFileContent = fs.readFileSync('owners.txt', 'utf-8')
            console.log('ownersFileContent: ',ownersFileContent)
            }
            catch(error) {
            console.error('Error reading file:', error);
            }
