name: Process File

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  process-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Run JavaScript Script
        run: |
          const fs = require('fs');

          function processLine(line, result) {
              const parts = line.trim().split(/\/|@/);
              let current = result;
              for (const part of parts) {
                  if (part) {
                      current = current[part] = current[part] || {};
                  }
              }
          }

          function readFile(filePath) {
              const result = {};
              const content = fs.readFileSync(filePath, 'utf-8');
              const lines = content.split('\n');
          
              for (const line of lines) {
                  processLine(line, result);
              }
          
              return result;
          }

          function formatOutput(data) {
              const output = {};
              for (const [key, value] of Object.entries(data)) {
                  if (typeof value === 'object') {
                      output[key] = formatOutput(value);
                  } else {
                      output[key] = { reviewers: [value] };
                  }
              }
              return output;
          }

          const filePath = 'your_file.txt';  // Replace with the actual path to your file
          const data = readFile(filePath);
          const output = formatOutput(data);
          console.log(output);
