name: Reviews
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Execute script
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const data = {};
            const lines = fs.readFileSync('owners', 'utf-8').split('\n');
            console.log(`lines: `,lines);

            lines.forEach(line => {
              const parts = line.trim().split(' ');
              console.log(`parts: `,parts);
              const nestedKeys = parts[0].split('/').filter(str => str !== '');
              console.log(`nestedKeys: `,nestedKeys);
            })
            
            console.log(`Hello`)
            return "Hello!"
