name: Reviews
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Execute script
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const data = {};
            const lines = fs.readFileSync('owners', 'utf-8').split('\n');
            console.log("lines: ",lines)
            
            lines.forEach(line => {
              const parts = line.trim().split(' ');
              let currentObj = data;
              const nestedKeys = part.split('/');
              nestedKeys.forEach(key => {
                currentObj = currentObj[key] = currentObj[key] || {"reviewers": []};
              })
              currentObj["reviewers"].concat(parts.slice(1))
              console.log("currentObj: ",currentObj)
            })
#            if (data.reviewers) {
#              data.reviewers = Object.keys(data.reviewers);
#            }
            console.log(JSON.stringify(data, null, 2));
