name: Reviews
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Execute script
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const data = {};
            const lines = fs.readFileSync('owners', 'utf-8').split('\n');
            console.log(`lines: `,lines);

            lines.forEach(line => {
              # split the line into individual words
              const parts = line.trim().split(' ');
              console.log(`parts: `,parts);

              # split path into individual words
              const nestedKeys = parts[0].split('/').filter(str => str !== '');
              console.log(`nestedKeys: `,nestedKeys);
            })

            # get list of reviewers on PR (users + teams)
            const token = core.getInput('token');
            const reviews = await github.rest.pulls.listRequestedReviewers({
                          ...context.repo,
                          pull_number: context.payload.pull_request.number
                      });
            console.log(`reviews.data.users: `,reviews.data.users);

            for (const user of reviews.data.users) {
              console.log(`user: `,user)
              console.log(`user.login: `,user.login)
              console.log(`user.state: `,user.state)
            }

            console.log(`Hello`)
            return "Hello!"
