name: Reviews
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Execute script
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const data = {};
            const lines = fs.readFileSync('owners', 'utf-8').split('\n');
            console.log(`lines: `,lines);

            lines.forEach(line => {
              // split the line into individual words
              const parts = line.trim().split(' ');
              console.log(`parts: `,parts);

              // split path into individual words
              const nestedKeys = parts[0].split('/').filter(str => str !== '');
              console.log(`nestedKeys: `,nestedKeys);
            })

            // get list of reviews on PR
            const token = core.getInput('token');
            const reviews = await github.rest.pulls.listReviews({
                          ...context.repo,
                          pull_number: context.payload.pull_request.number
                      })
            console.log(`list of reviews: `,reviews);

            const approved_users: Set<String> = new Set();
            for (const review of reviews.data) {
              if (review.state === `APPROVED` && review.user) {
                // Add the user name to the set
                approved_users.add(review.user.login)
              }
            }
            console.log(`approved_users: `,approved_users);

            console.log(`Hello`)
            return "Hello!"
